# Book settings
title: Machine Learning Operations (MLOps)
author: Dominik Kreuzberger, Niklas Kühl, Sebastian Hirschl
logo: ""

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: mlops-principles.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/your-username/mlops-principle # Online location of your book
  path_to_book: "" # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Launch button configuration
launch_buttons:
  notebook_interface: classic # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: "" # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe: false # Add a thebe button to pages (requires the repository to run on Binder)

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
